### PR TITLE
Create LICENSE.md

### LINKED ISSUE #4: Add README and LICENSE files
Adding those files at the top-level would be great. The README should have a few notes on what this is, and probably link to the subfolders.

### PR DESCRIPTION
**Pull request by penev92**
Adding a GLPv3 license that matches what [OpenRA/OpenRA](https://github.com/OpenRA/OpenRA) uses.

Closes #4.

### CODE REVIEW

**Comment by letmaik** [comment]
File extension should not be `.md`, but rather without, or if anything then `.txt`.

**Comment by penev92** [comment]
The GitHub interface told me "use either `LICENSE` or `LICENSE.md`" and since I find extensionless files weird I went with the latter 🤷‍♂️ 
I guess I could drop the extension if it's an issue.

**Comment by letmaik** [comment]
Well, your license is not formatted as markdown, and it produces bad rendering, see the preview in the PR. So then I would really leave out the extension.

**Comment by penev92** [comment]
Done.

**Pull request merged**
